# Generated by Django 5.1.4 on 2024-12-26 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('iso_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.TextField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_source', models.FloatField()),
                ('amount_target', models.FloatField()),
                ('convert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_source', to='main.currency')),
                ('currency_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
                ('rate_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_source', to='main.rate')),
                ('rate_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rate')),
            ],
        ),
    ]
